# -*- coding: utf-8 -*-
"""progetto Sviluppo di un assistente virtuale multimodale per la finanza personale .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/103Lu7A5bVSWXqol64rrLnuMvxuYtzVyU

nel progetto dello sviluppo di un assistente virtuale multimodale per la finanza personale  ho usato google colab. l'assitente virtuale trascrive l'audio con Whisper, interpreta le richieste con NLP zero-shot, analizza un dataset di transazioni fittizie e genera risposte personalizzate. Il flusso conversazionale è gestito tramite LangGraph e supporta sia input vocali che testuali.


Note personali: Ho rispettato tutto ciò che era previsto, ma ho anche pensato a come evolvere il progetto, ad esempio con una rappresentazione visiva delle spese settimanali. Aggiungere un grafico con matplotlib per renderebbe le risposte più immediate e comprensibili, migliorando l’esperienza utente.
"""

!pip install -U openai-whisper

!pip install -U transformers

!pip install langgraph

!pip install torchaudio
!apt-get install ffmpeg -y

#import moduli
import whisper
from transformers import pipeline
from langgraph.graph import StateGraph
import os
from typing import TypedDict

#dataset fittizio
dati_utente = {
    "transazioni": [
        {"data": "2025-07-01", "categoria": "Spesa", "importo": 30.5},
        {"data": "2025-07-02", "categoria": "Trasporti", "importo": 12.0},
        {"data": "2025-07-03", "categoria": "Divertimento", "importo": 20.0},
        {"data": "2025-07-04", "categoria": "Spesa", "importo": 18.5}
    ]




}

#riconoscimento automatico del parlato con Whisper
def riconoscimento_whisper(state: Dict):
    try:
        audio_path = state["audio_path"]
        modello = whisper.load_model("small")
        risultato = modello.transcribe(audio_path, language="it")
        testo = risultato["text"]
        return {**state, "testo": testo}
    except Exception as e:
        print(f"[ASR] errore nel riconoscimento: {e}")
        return {**state, "testo": "non sono riuscito a capire il tuo messaggio, vuoi riprovare?"}

#comprensione del linguaggio naturale: analisi di intento
#Utilizziamo una pipeline di zero-shot classification di Hugging Face (modello BART-large-mnli)
nlp = pipeline("zero-shot-classification", model="facebook/bart-large-mnli")

def analizza_testo(state: Dict):
    try:
        testo = state["testo"]
        intenti = ["verifica_spesa_settimanale", "spesa_per_categoria"]
        risultato = nlp(testo, candidate_labels=intenti)
        intento = risultato["labels"][0] if risultato["scores"][0] > 0.5 else "intento_non_rilevato"
        print(f"[NLP] {intento}")
        return {**state, "intento": intento}
    except Exception as e:
        print(f"[NLP] errore: {e}")
        return {**state, "intento": "intento_non_rilevato"}

# === Funzione di Supporto ===
def calcola_spesa_per_categoria(categoria):
    return sum(t["importo"] for t in dati_utente["transazioni"] if t["categoria"].lower() == categoria.lower())

#generazione risposta
def genera_risposta(state: dict):
    intento = state.get("intento")
    testo = state.get("testo")

    if intento == "verifica_spesa_settimanale":
        totale = sum(t["importo"] for t in dati_utente["transazioni"])
        risposta = f"Hai speso {totale} euro questa settimana."


    elif intento == "spesa_per_categoria":
        for categoria in ["spesa", "trasporti", "divertimento"]:
            if categoria in testo.lower():
                totale_cat = calcola_spesa_per_categoria(categoria)
                risposta = f"Hai speso {totale_cat} euro per la categoria {categoria}."
                break
        else:
            risposta = "Per favore, specifica una categoria di spesa."

    else:
        risposta = "Mi dispiace, non ho capito la tua richiesta."

    print(f"[Risposta] {risposta}")
    return {**state, "risposta": risposta}

#langGraph: flusso conversazionale
#Definiamo un grafo di stati per orchestrare il flusso dell'assistente
class StatoAssistente(TypedDict):
    audio_path: str
    testo: str
    intento: str
    risposta: str

graph = StateGraph(StatoAssistente)


graph = StateGraph(dict)
graph.add_node("ASR", riconoscimento_whisper)
graph.add_node("NLP", analizza_testo)
graph.add_node("risposta", genera_risposta)
graph.set_entry_point("ASR")
graph.add_edge("ASR", "NLP")
graph.add_edge("NLP", "risposta")

assistant = graph.compile()

#esecuzione
def assistente_virtuale(audio_path):
    print("Inizio interazione finanziaria...")

    if not os.path.exists(audio_path) or not audio_path:
        print("[INFO] Nessun audio trovato, uso dati di esempio.")

        stato_iniziale = {
            "audio_path": audio_path,
            "testo": "Quanto ho speso questa settimana?"
        }

        # Simuli l'analisi NLP e la generazione risposta direttamente
        stato_iniziale = analizza_testo(stato_iniziale)
        risultato_finale = genera_risposta(stato_iniziale)
    else:
        stato_iniziale = {"audio_path": audio_path}
        risultato_finale = assistant.invoke(stato_iniziale)

    print(f"\n[RISPOSTA ASSISTENTE]:\n{risultato_finale['risposta']}\n")
    print("Interazione completata")

if __name__== '__main__':
   assistente_virtuale("") #inserisci file audio